<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="20160229-115937" name="false" tests="1" failures="1" timestamp="5 May 2016 03:06:50 GMT" time="1.272" errors="0">
  <testcase name="runTestCase" time="1.24" classname="com.creditease.xyuan.httpTest.test.testngRun">
    <failure type="java.lang.Exception" message="org.apache.http.conn.HttpHostConnectException: Connect to 10.36.40.84:8888 [/10.36.40.84] failed: Connection refused: connect">
      <![CDATA[java.lang.Exception: org.apache.http.conn.HttpHostConnectException: Connect to 10.36.40.84:8888 [/10.36.40.84] failed: Connection refused: connect
	at com.creditease.xyuan.httpTest.test.testngRun.runTestCase(testngRun.java:36)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.runTestNG(TestNGProcesser.java:138)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.runTestCaseByTag(TestNGProcesser.java:108)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.runSequenceTests(TestNGProcesser.java:73)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.test(TestNGProcesser.java:49)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.main(TestNGProcesser.java:25)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- runTestCase -->
</testsuite> <!-- false -->
