<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="1272" started-at="2016-05-05T03:06:49Z" finished-at="2016-05-05T03:06:50Z">
    <groups>
    </groups>
    <test name="false" duration-ms="1272" started-at="2016-05-05T03:06:49Z" finished-at="2016-05-05T03:06:50Z">
      <class name="com.creditease.xyuan.httpTest.test.testngRun">
        <test-method status="FAIL" signature="runTestCase(org.dom4j.Element)[pri:0, instance:com.creditease.xyuan.httpTest.test.testngRun@1fd0d1]" name="runTestCase" duration-ms="1240" started-at="2016-05-05T11:06:49Z" data-provider="test" finished-at="2016-05-05T11:06:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.dom4j.tree.DefaultElement@b78c9d [Element: <model attributes: [org.dom4j.tree.DefaultAttribute@70c0d1 [Attribute: name name value "newsmth"]]/>]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[org.apache.http.conn.HttpHostConnectException: Connect to 10.36.40.84:8888 [/10.36.40.84] failed: Connection refused: connect]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: org.apache.http.conn.HttpHostConnectException: Connect to 10.36.40.84:8888 [/10.36.40.84] failed: Connection refused: connect
	at com.creditease.xyuan.httpTest.test.testngRun.runTestCase(testngRun.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.runTestNG(TestNGProcesser.java:138)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.runTestCaseByTag(TestNGProcesser.java:108)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.runSequenceTests(TestNGProcesser.java:73)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.test(TestNGProcesser.java:49)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.main(TestNGProcesser.java:25)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runTestCase -->
      </class> <!-- com.creditease.xyuan.httpTest.test.testngRun -->
    </test> <!-- false -->
  </suite> <!-- Default Suite -->
</testng-results>
