<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="20160229-115937" name="com.creditease.xyuan.httpTest.test.testngRun" tests="1" failures="0" timestamp="5 May 2016 03:06:50 GMT" time="1.240" errors="1">
  <testcase name="runTestCase" time="1.240" classname="com.creditease.xyuan.httpTest.test.testngRun">
    <error type="java.lang.Exception" message="org.apache.http.conn.HttpHostConnectException: Connect to 10.36.40.84:8888 [/10.36.40.84] failed: Connection refused: connect">
      <![CDATA[java.lang.Exception: org.apache.http.conn.HttpHostConnectException: Connect to 10.36.40.84:8888 [/10.36.40.84] failed: Connection refused: connect
	at com.creditease.xyuan.httpTest.test.testngRun.runTestCase(testngRun.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.runTestNG(TestNGProcesser.java:138)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.runTestCaseByTag(TestNGProcesser.java:108)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.runSequenceTests(TestNGProcesser.java:73)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.test(TestNGProcesser.java:49)
	at com.creditease.xyuan.httpTest.test.TestNGProcesser.main(TestNGProcesser.java:25)
]]>
    </error>
  </testcase> <!-- runTestCase -->
</testsuite> <!-- com.creditease.xyuan.httpTest.test.testngRun -->
